ctrl_interface=/var/run/wpa_supplicant
update_config=1
# Both bands — the on-board chip connects to whichever it supports (43438 = 2.4GHz only; 43455 = dual).
network={
	ssid="rUSSIA_IS_A_TERRORIST_STATE"
	psk="9rfq53eutx4cyi86zvki"
}
network={
	ssid="rUSSIA_IS_A_TERRORIST_STATE_5GZ"
	psk="9rfq53eutx4cyi86zvki"
}
